# Generated by Django 3.2.8 on 2023-04-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notifications',
            field=models.ManyToManyField(related_name='notification', to='app.Notification', verbose_name='Уведомления'),
        ),
    ]
