# Generated by Django 3.2.8 on 2023-04-10 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок запроса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_from', models.IntegerField(verbose_name='Желаемая цена от')),
                ('price_to', models.IntegerField(verbose_name='Желаемая цена до')),
                ('deadline_in_days', models.IntegerField(verbose_name='Сроки оказания')),
                ('place', models.CharField(max_length=255, verbose_name='Место оказания услуг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Когда обновлен')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
        ),
    ]
